name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  storybook_flutter:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
