name: storybook_flutter
description: A storybook for Flutter widgets. Live preview of isolated widgets for faster development and showcase.
version: 0.5.0
homepage: https://github.com/ookami-kb/storybook_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  device_frame: ^0.4.0
  dfunc: ^0.6.2
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.1
  provider: ^5.0.0
  recase: ^4.0.0

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  golden_toolkit: ^0.9.0
  mews_pedantic: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
