name: storybook_flutter
description: A storybook for Flutter widgets. Live preview of isolated widgets for faster development and showcase.
version: 0.4.1+2
homepage: https://github.com/ookami-kb/storybook_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  provider: ^5.0.0
  recase: ^4.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.2.0

flutter:
  uses-material-design: true
