name: storybook_flutter
description: A storybook for Flutter widgets. Live preview of isolated widgets
  for faster development and showcase.
version: 0.11.2+2
homepage: https://github.com/ookami-kb/storybook_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  device_frame: ^1.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.0
  nested: ^1.0.0
  pointer_interceptor: ^0.9.3
  provider: ">=6.0.0 <7.0.0"
  recase: ^4.0.0

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  golden_toolkit: ^0.9.0
  mews_pedantic: ^0.9.0+2
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
