name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^0.7.1
  flutter:
    sdk: flutter
  storybook_device_preview:
    path: ..
  storybook_flutter: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.2.0

flutter:
  uses-material-design: true
